#
#                        ______           _             _____ _           _
#                       |___  /          (_)           /  __ \ |         | |
#                          / /  ___  _ __ _  ___  _ __ | /  \/ |__   __ _| |_
#                         / /  / _ \| '__| |/ _ \| '_ \| |   | '_ \ / _` | __|
#                       ./ /__| (_) | |  | | (_) | | | | \__/\ | | | (_| | |_
#                       \_____/\___/|_|  |_|\___/|_| |_|\____/_| |_|\__,_|\__|
#
#                                           by Lukatjee
#             https://www.spigotmc.org/resources/zorionchat-quick-and-easy-chat-manager.86984/
#
# Config version (DO NOT CHANGE THIS).
version: "1.0"

# Edit the chat format here, cannot be disabled as it is the base feature of this plugin.
chat-format: "%player_displayname% &8Â» &f"

# Edit the first join message here, set to "" to disable.
first-join-message: "&8[&a&l+&8]&6 %player_name%&7 joined the server for the first time."

# Edit the join message here, set to "" to disable the custom join message.
join-message: "&8[&a&l+&8]&6 %player_name%&7 joined the server."

# Edit the quit message here, set to "" to disable the custom auit message.
quit-message: "&8[&c&l-&8]&6 %player_name%&7 quit the server."

# Below you can configure all plugin messages to your likings, these messages support hex
# and vanilla color codes. If you translated these messages and want to contribute
# to the project you can send the translation(s) to me on Discord.

# Edit the no permission message here, supports vanilla and hex color codes
no-permission: "&cOh no! It appears you do not have the permission to execute this command."

# Edit the reload command message here, supports vanilla and hex color codes.
reload-message: "&aSuccessfully reloaded the chat configuration."
